/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Image, Text, View } from "@aws-amplify/ui-react";
export default function GlobalAjedrez(props) {
  const { jugadores, overrides, ...rest } = props;
  return (
    <View
      width="264px"
      height="131px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "GlobalAjedrez")}
      {...rest}
    >
      <View
        width="264px"
        height="131px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,82,141,1)"
        {...getOverrideProps(overrides, "Rectangle 75")}
      ></View>
      <Image
        width="43.56%"
        height="91.6%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="3.82%"
        bottom="4.58%"
        left="2.27%"
        right="54.17%"
        border="1px SOLID rgba(255,255,255,1)"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "ajedrecista 1")}
      ></Image>
      <View
        width="115px"
        height="19px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="80.92%"
        bottom="4.58%"
        left="2.27%"
        right="54.17%"
        border="1px SOLID rgba(255,255,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(193,26,26,1)"
        {...getOverrideProps(overrides, "Rectangle 76")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="83.21%"
        bottom="7.63%"
        left="6.06%"
        right="57.95%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.nombre}
        {...getOverrideProps(overrides, "Fernando Gutierrez")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="6.11%"
        bottom="84.73%"
        left="48.48%"
        right="38.26%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Ciudad"
        {...getOverrideProps(overrides, "Ciudad")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="6.11%"
        bottom="84.73%"
        left="74.62%"
        right="3.79%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.ciudad}
        {...getOverrideProps(overrides, "Guanajuato")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="20.61%"
        bottom="70.23%"
        left="74.62%"
        right="18.94%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajecombates}
        {...getOverrideProps(overrides, "112")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="35.11%"
        bottom="55.73%"
        left="75%"
        right="19.7%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajetriunfos}
        {...getOverrideProps(overrides, "90")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="49.62%"
        bottom="41.22%"
        left="75.38%"
        right="20.08%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajederrotas}
        {...getOverrideProps(overrides, "10")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="64.12%"
        bottom="26.72%"
        left="76.89%"
        right="20.45%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajeempates}
        {...getOverrideProps(overrides, "2")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="20.61%"
        bottom="70.23%"
        left="48.48%"
        right="35.98%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Partidas"
        {...getOverrideProps(overrides, "Partidas")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="35.11%"
        bottom="55.73%"
        left="48.11%"
        right="35.23%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Ganadas"
        {...getOverrideProps(overrides, "Ganadas")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="49.62%"
        bottom="41.22%"
        left="48.11%"
        right="35.23%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Perdidas"
        {...getOverrideProps(overrides, "Perdidas")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="64.12%"
        bottom="26.72%"
        left="48.11%"
        right="31.06%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Empatadas"
        {...getOverrideProps(overrides, "Empatadas")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="16.94318199157715px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="81.68%"
        bottom="5.34%"
        left="59.47%"
        right="29.92%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="ELO"
        {...getOverrideProps(overrides, "ELO")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="16.94318199157715px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="81.68%"
        bottom="5.34%"
        left="75.38%"
        right="11.36%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.ajedrezelo}
        {...getOverrideProps(overrides, "1230")}
      ></Text>
    </View>
  );
}
