/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Flex, Image, Text, View } from "@aws-amplify/ui-react";
export default function GlobalBox(props) {
  const { jugadores, overrides, ...rest } = props;
  return (
    <View
      width="264px"
      height="200px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "GlobalBox")}
      {...rest}
    >
      <View
        width="264px"
        height="200px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        {...getOverrideProps(overrides, "Rectangle 72")}
      ></View>
      <Flex
        gap="8px"
        direction="row"
        width="46px"
        height="22px"
        justifyContent="center"
        alignItems="center"
        position="absolute"
        top="81.5%"
        bottom="7.5%"
        left="79.55%"
        right="3.03%"
        borderRadius="8px"
        padding="0px 16px 0px 16px"
        backgroundColor="rgba(238,238,238,1)"
        {...getOverrideProps(overrides, "buttonRecord")}
      >
        <Text
          fontFamily="Inter"
          fontSize="10px"
          fontWeight="500"
          color="rgba(0,0,0,1)"
          lineHeight="15px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Record"
          {...getOverrideProps(overrides, "Record")}
        ></Text>
      </Flex>
      <View
        width="140px"
        height="141px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="2%"
        bottom="27.5%"
        left="45.45%"
        right="1.52%"
        border="1px SOLID rgba(255,255,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(22,21,21,1)"
        {...getOverrideProps(overrides, "Rectangle 74")}
      ></View>
      <View
        width="111px"
        height="141px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="2%"
        bottom="27.5%"
        left="1.52%"
        right="56.44%"
        border="2px SOLID rgba(255,255,255,1)"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "CAM01731 1")}
      ></View>
      <View
        width="111px"
        height="19px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63%"
        bottom="27.5%"
        left="1.52%"
        right="56.44%"
        border="1px SOLID rgba(255,255,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(188,12,12,0.8)"
        {...getOverrideProps(overrides, "Rectangle 73")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="111px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="64.5%"
        bottom="29.5%"
        left="1.52%"
        right="56.44%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.nombre}
        {...getOverrideProps(overrides, "EL GALLO LOPEZ")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="6%"
        bottom="86.5%"
        left="48.86%"
        right="25%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="COMBATES"
        {...getOverrideProps(overrides, "COMBATES")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="19.5%"
        bottom="73%"
        left="48.86%"
        right="25.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="VICTORIAS"
        {...getOverrideProps(overrides, "VICTORIAS")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="32%"
        bottom="60.5%"
        left="48.86%"
        right="26.52%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="DERROTAS"
        {...getOverrideProps(overrides, "DERROTAS")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="45.5%"
        bottom="47%"
        left="48.86%"
        right="29.55%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="EMPATES"
        {...getOverrideProps(overrides, "EMPATES")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58%"
        bottom="34.5%"
        left="49.24%"
        right="20.08%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="KNOCK OUTS"
        {...getOverrideProps(overrides, "KNOCK OUTS")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="26px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="6%"
        bottom="86.5%"
        left="84.85%"
        right="5.3%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajecombates}
        {...getOverrideProps(overrides, "24")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="25px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="19.5%"
        bottom="73%"
        left="85.23%"
        right="5.3%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajetriunfos}
        {...getOverrideProps(overrides, "10")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="32%"
        bottom="60.5%"
        left="86.74%"
        right="7.2%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajederrotas}
        {...getOverrideProps(overrides, "8")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="45.5%"
        bottom="47%"
        left="86.74%"
        right="7.2%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxajeempates}
        {...getOverrideProps(overrides, "6")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="12px"
        fontWeight="700"
        color="rgba(243,219,0,1)"
        lineHeight="14.522727012634277px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="59%"
        bottom="33.5%"
        left="88.64%"
        right="8.33%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxKO}
        {...getOverrideProps(overrides, "5")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="75.5%"
        bottom="18.5%"
        left="1.52%"
        right="75.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="CATEGORIA"
        {...getOverrideProps(overrides, "CATEGORIA")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="83.5%"
        bottom="10.5%"
        left="1.52%"
        right="78.79%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="GIMNASIO"
        {...getOverrideProps(overrides, "GIMNASIO")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="91.5%"
        bottom="2.5%"
        left="1.52%"
        right="83.33%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="CIUDAD"
        {...getOverrideProps(overrides, "CIUDAD")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="116px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="91.5%"
        bottom="2.5%"
        left="29.55%"
        right="26.52%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.ciudad}
        {...getOverrideProps(overrides, "GUADALAJARA")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="115px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="83.5%"
        bottom="10.5%"
        left="29.55%"
        right="26.89%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.boxgimnasio}
        {...getOverrideProps(overrides, "NI\u00D1OS HEROES")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="10px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="12.102272033691406px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="115px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="75.5%"
        bottom="18.5%"
        left="29.55%"
        right="26.89%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children={jugadores?.categoria}
        {...getOverrideProps(overrides, "PESO MOSCA")}
      ></Text>
      <Image
        width="37.5%"
        height="58%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="5%"
        bottom="37%"
        left="3.79%"
        right="58.71%"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        src={jugadores?.foto}
        {...getOverrideProps(overrides, "boxeador 1")}
      ></Image>
    </View>
  );
}
